# Generated by Django 4.1.7 on 2023-03-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("power", models.IntegerField()),
            ],
            options={
                "verbose_name": "Move",
                "verbose_name_plural": "Moves",
            },
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("order", models.IntegerField()),
                ("power", models.IntegerField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                (
                    "moves",
                    models.ManyToManyField(related_name="pokemons", to="api.move"),
                ),
            ],
            options={
                "verbose_name": "Pokemon",
                "verbose_name_plural": "Pokemons",
            },
        ),
    ]
