# Generated by Django 4.1.7 on 2023-03-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="power",
            field=models.IntegerField(default=0),
        ),
    ]
