# Generated by Django 4.1.7 on 2023-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_move_power"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="power",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="power",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
